# Generated by Django 5.2.8 on 2025-11-27 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('expense_date', models.DateField()),
                ('merchant_name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('entry_method', models.CharField(choices=[('manual', 'Manual Entry'), ('receipt_scan', 'Receipt Scan'), ('voice_input', 'Voice Input'), ('text_parsing', 'Text Parsing')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='categories.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'EXPENSE',
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='receipts/%Y/%m/')),
                ('file_type', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ocr_text', models.TextField(blank=True, null=True)),
                ('expense', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='expenses.expense')),
            ],
            options={
                'db_table': 'RECEIPT',
            },
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'expense_date'], name='EXPENSE_user_id_9bd6e4_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['category'], name='EXPENSE_categor_f1b16e_idx'),
        ),
    ]
