# Generated by Django 5.2.8 on 2025-11-27 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.JSONField()),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('extraction_method', models.CharField(choices=[('ocr_vision_api', 'OCR Vision API'), ('nlp_voice_processing', 'NLP Voice Processing'), ('nlp_text_parsing', 'NLP Text Parsing')], max_length=50)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_extractions', to='expenses.expense')),
            ],
            options={
                'db_table': 'AI_EXTRACTION',
                'ordering': ['-processed_at'],
            },
        ),
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('weekly_summary', 'Weekly Summary'), ('monthly_summary', 'Monthly Summary'), ('budget_alert', 'Budget Alert'), ('spending_pattern', 'Spending Pattern'), ('prediction', 'Prediction'), ('recommendation', 'Recommendation')], max_length=20)),
                ('insight_data', models.JSONField(blank=True, null=True)),
                ('message', models.TextField()),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'AI_INSIGHT',
                'ordering': ['-generated_at'],
            },
        ),
    ]
